### PR TITLE
Cleanup and click countries

### PR DESCRIPTION
**Pull request by diablourbano**
This is a huge PR, basically I cleaned up the code moving the code from main.js to a more structured organization with functions that can be called and be located in other files, this allows main.js to be a more readable file and allows to reuse.

The map can be clicked, once the user clicks a country the regular workflow (automatic and random) will be stopped and the news related to the country clicked will be presented, there's a 'news control' with a play/pause, backward/forward buttons and a shuffle.

I also change the colors of the map, basically we want the user to focus on the news and the contrast between brown, blue and bright red is unnecessary so I reduced the contrast to white/gray/black.

Please review it and let me know what do you think.

### CODE REVIEW

**Comment by diablourbano** [comment]
As requested by @completedespair I revert the colors of the world-map to the original ones

**Comment by dhinus** [comment]
@diablourbano please note the Juicer API URL has changed. I have updated the master branch, please merge the master branch into this branch and resolve the conflicts.

**Comment by diablourbano** [comment]
@dhinus I just resolved the api url and the query name conflicts, if you consider we can merge this branch with master, please do it, also, I don't know if you or someone else is in charge to deploy it, but it would be great to deploy it so anybody can test it.

**Comment by dhinus** [comment]
@diablourbano I'll test your branch locally and if it looks good I'll merge it & deploy it before the end of the week!

**Comment by diablourbano** [comment]
@dhinus any news about this PR?

also I'm going to create another PR in the features_with_juicer_api branch, if you accept that it will contain this changes also, just to let you know.

**Comment by dhinus** [comment]
@diablourbano oops sorry, too many things in my todo list. I tested this branch and it looks OK to me, I'm gonna merge it and deploy it now.

**Pull request merged**
